name: portraitpy-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.12
  - pre-commit
  - pytest-cov
  - pytest-sugar
  - pip:
      - git+https://github.com/numpy/numpy
      - git+https://github.com/matplotlib/matplotlib
